import Promo from "@/components/promo/promo";
import Services from "@/components/service/services";
import Head from "next/head";
import { Services as serviceData } from "@/data/services";

export default function Home() {
  return (
    <>
      <Head>
        <title>Novena - Health & Care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Promo />
      <Services
        title={serviceData.title}
        description={serviceData.description}
        serviceItems={serviceData.serviceItems}
      />
    </>
  );
}
