import Banner from "@/components/banner/banner";
import Head from "next/head";
import bg from '@assets/images/bg/slider-bg-1.jpg';
import HomePageCard from "@/components/infocard/infocard";
import Promo from "@/components/promo/promo";
import {StatisticItems} from "@/data/statistics"
import Statistics from "@/components/statistics/statistics";
import Services from "@/components/service/services";
import {Services as ServicesData} from "@/data/services"
import Clients from "@/components/clients/clients";
import { Client } from "@/data/clients";
import Testimonials from "@/components/testimonial/testimonials";
import {TestimonialHeader} from "@/data/testimonial"

export default function Home() {
  return (
    <>
      <Head>
        <title>Novena - Health & Care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner title={"Total Health care solution"} heading={"Your most trusted health partner"} description={"A repudiandae ipsam labore ipsa voluptatum quidem quae laudantium quisquam aperiam maiores sunt fugit, deserunt rem suscipit placeat."} ctaText={"Make appoinment"} ctaLink={"appoinment.html"} bgImg={bg.src}/>
      
      <Promo/>
      <Statistics statisticItems={StatisticItems}/>
      <Services title={ServicesData.title} description={ServicesData.description} serviceItems={ServicesData.serviceItems}/>
      <Testimonials title={TestimonialHeader.title} description={TestimonialHeader.description} items={TestimonialHeader.items}/>
      <Clients title={Client.title} description={Client.description} clientItems={Client.clientItems}/>
    </>
  );
}
