import Banner from '@/components/banner/banner'
import Head from 'next/head'
import bg from '@assets/images/bg/slider-bg-1.jpg'
import Promo from '@/components/promo/promo'
import { StatisticItems } from '@/data/statistics'
import Statistics from '@/components/statistics/statistics'
import Services from '@/components/service/services'
import { Services as ServicesData } from '@/data/services'
import Clients from '@/components/clients/clients'
import { Client } from '@/data/clients'
import Testimonial from '@/components/testimonial/testimonials'
import InfoCard from '@/components/infocard/infocard'
import { InfoCards } from '@/data/info-card'
import { TestimonialsProps } from '@/library/types'
import { NextPageWithLayout } from '@/library/types'

const Home: NextPageWithLayout<{
  testimonials: TestimonialsProps
  services: ServicesData
}> = (props: { testimonials: TestimonialsProps; services: ServicesData }) => {
  return (
    <>
      <Head>
        <title>Novena - Health & Care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner
        title={'Total Health care solution'}
        heading={'Your most trusted health partner'}
        description={
          'A repudiandae ipsam labore ipsa voluptatum quidem quae laudantium quisquam aperiam maiores sunt fugit, deserunt rem suscipit placeat.'
        }
        ctaText={'Make appoinment'}
        ctaLink={'appoinment.html'}
        bgImg={bg.src}
      />
      <InfoCard cards={InfoCards} />
      <Promo />
      <Statistics statisticItems={StatisticItems} />
      <Services
        title={props.services.title}
        description={props.services.description}
        serviceItems={props.services.serviceItems}
      />
      <Testimonial
        title={props.testimonials.title}
        description={props.testimonials.description}
        testimonials={props.testimonials.testimonials}
      />
      <Clients
        title={Client.title}
        description={Client.description}
        clientItems={Client.clientItems}
      />
    </>
  )
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  let res = await fetch('http://localhost:3000/api/testimonials')
  const testimonials = (await res.json()) as TestimonialsProps

  res = await fetch('http://localhost:3000/api/services')
  const services = (await res.json()) as ServicesData

  // Pass data to the page via props
  return {
    props: {
      testimonials: testimonials,
      services: services,
    },
  }
}

export default Home
